### PR TITLE
Package refactor

### PR DESCRIPTION
**Pull request by silvergasp**
I have just updated the project structure to be more idiomatic with golang and to simplify the installation and usage. I have also updated the installation guide on the readme to reflect the changes. I have not tested this addition as it would require forking to a seperate repo and merging back. I will do the above if you think that the changes are worthwhile, otherwise you are welcome to merge back to the master.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
Cheers for updating gitignore. I didn't notice that it was still using the python one from when the entire project was in Python instead of Go.

Because the telemetry software contains a couple programs and isn't just a single binary, I thought I'd pull all the common functionality out into its own library and then the binaries can import that functionality and use it. This is roughly the directory structure I was thinking of having:

* github.com/Curtin-Motorsport-Team/telemetry/
  * *.go
  * README.md
  * ...
  * telemetry-listener/
    * main.go
  * telemetry-server/
    * main.go

Or even put the folders with binaries inside a `tools` directory, so you can get `telemetry-listener` and `telemetry-server` with:

```
$ go get github.com/Curtin-Motorsport-Team/telemetry/tools/...
```
> **Note:** Now that the repo has been moved from my personal account to the CMT organisation I was wanting to rename the repo and package to tidy it up. Something like `github.com/Curtin-Motorsport-Team/telemetry` would be nice. Some bikeshedding may be necessary to think of an appropriate name. I'm the only one who's downloaded the library so far, so backwards compatibility isn't an issue.

I'm not a big fan of the `telemetryLib` name though. Adding `Lib` to the name feels kinda redundant seeing as if you're importing it, it has to be a library. Also, the import path would then be `github.com/Curtin-Motorsport-Team/cmt-telemetry-software/telemetryLib` which reminds me a lot of the the stutter in Java. It also means that `github.com/Curtin-Motorsport-Team/cmt-telemetry-software` isn't actually a valid Go library, so perhaps keeping the library stuff in the repo's root directory would feel more idiomatic? I dunno, that's what I've seen most other projects do anyway.

As an aside, you'll probably want to change the package name in `telemetry/main.go` to package main because all executables in Go must be in a `main` package. Otherwise you've got a library which just happens to have a private function called `main()`. That's just a one line fix though.

**Comment by silvergasp** [comment]
Yeah fair enough, I agree with the changing telemetyLib. It was more just emphasizing that you should have a different name for each thing rather than having a /bin directory with your main.go. Tis a bit misleading as you already have a $GOPATH/bin directory. I also was more just pushing towards using the actual package management in golang, rather than using it as a bit of an afterthought. It just makes it easier to kind to make it a bit more modular and easier to install. So I agree with everything that you have done. And your probably right about the invalid go repo, although not sure. Also I wouldn't modularize it too much as it will become a bit of fragmented. But otherwise it looks really good.

**Comment by silvergasp** [comment]
I think that having a seperate directory for tools would be a good idea as well.

**Comment by Michael-F-Bryan** [comment]
I went through and applied most of the changes you've proposed. I didn't merge your PR though because there have been several changes since then and it's easier to rewrite a couple package lines in master than resolve a bunch of merge conflicts manually, hope you don't mind.

The package still has a couple warts and parts where it's on the verge of turning into spaghetti code, but I'm planning on waiting for the next track day to get a better idea of what else could do with fixing/refactoring.

**Comment by silvergasp** [comment]
Im fine with that whatever works out to be easiest

**Pull request closed without merging**
